name: garista_pos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^5.0.1
  connectivity_plus: ^6.0.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_remix: ^0.0.3
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  flutter_advanced_switch: ^3.1.0
  lottie: ^3.1.2
  dotted_border: ^2.1.0
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  provider: ^6.1.2
  multi_dropdown: ^2.0.0
  flutter_isolate: ^2.1.0
  file_picker: ^8.1.2
  network_info_plus: ^6.0.1
  ping_discover_network_forked: ^0.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.3
  google_maps_flutter: ^2.9.0
  proste_indexed_stack: ^0.2.4
  image_cropper: ^8.0.2
  geolocator: ^13.0.1
  osm_nominatim: ^3.0.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  calendar_date_picker2: ^1.1.7
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  flutter_esc_pos_utils: ^1.0.1
  drag_and_drop_lists: ^0.4.1
  flutter_logs: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.9
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  mac: true
  remove_alpha_ios: true
  image_path: 'assets/images/png/app_logo.png'

  msix_config:
    display_name: Foodyman POS App
    publisher_display_name: Githubit
    identity_name: org.foodyman.pos
    msix_version: 1.0.0.0
    logo_path: D:\post_app_foodyman-main\post_app_foodyman\assets\images\png\app_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/svg/
    - assets/lottie/
    - assets/
    - assets/images/
